#!/bin/bash
echo "-Making scripts executable"
sudo chmod +x ~/.i3/compile ~/.i3/wrapper
echo "-Compiling config"
bash $HOME/.i3/compile
echo "-Copying xsession"
sudo cp $HOME/.i3/i3-wrapper.desktop /usr/share/xsessions/i3-wrapper.desktop
echo "Done"
